stages:
  - name: check configuration
    if: branch IN (travis, master)
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - sudo apt-get update
  - sudo apt-get -y install zstd libdbus-glib-1-dev libgtk2.0-dev

jobs:
  include:
    - stage: check configuration
      before_script: source ./pkg/automate/prepare.sh
      script: ./pkg/automate/test.sh
    - stage: deploy
      before_script: source ./pkg/automate/prepare.sh
      script: ./pkg/automate/deploy.sh
